FROM puckel/docker-airflow:1.10.9
RUN pip install requests
RUN pip install pandas
RUN pip install beautifulsoup4
RUN pip install pandas
RUN pip install requests
RUN pip install SQLAlchemy
RUN pip install db-sqlite3
RUN pip install pyspark
RUN pip install regex
RUN pip install nltk
RUN pip install stop-words
RUN pip install tokenizer
RUN pip install scikit-learn
RUN pip install python-math
RUN python -c "import nltk; nltk.download('punkt');nltk.download('vader_lexicon'); nltk.download('stopwords')"

